### ISSUE TITLE
Update the code for the python sample for the repo given 

### ISSUE THREAD

**Issue by mathagician** [pusher/hacktoberfest#35]
The link below [Django receipts](https://pusher.com/tutorials/read-receipts-django/) contains a github reference which does not work. Need to fix the same.

**Comment by mathagician** [comment]
@britneycodes  Please add this issue to the hacktober fest

**Comment by benjamin-tang-pusher** [comment]
Are you referring to the [Clone the project repository](https://github.com/samuelayo/pusher_django_message_delivery?_gl=1*7gjicg*_gcl_aw*R0NMLjE2NTg5NDAzNzMuQ2owS0NRand4SU9YQmhDckFSSXNBTDFRRkNiRVNHaE14ZlVZSFFvMEdOdk5BZjlEYW9VSll5WHVVRmQyRmtsZjRLNm1GbFRXREl2Wm1JSWFBbE9zRUFMd193Y0I.) on the top left? As that links to the repo correctly.

**Comment by benjamin-tang-pusher** [comment]
As I can't find the dead link (I've tried using a dead link checker for that page, and there wasn't one related to github), I'm going to close this issue.
