### ISSUE TITLE
Updates for  Hactoberfest Swags

### ISSUE THREAD

**Issue by kaggrwal** [pusher/hacktoberfest#50]
There is no communication regarding swags, Any updates regarding same?

**Comment by benw-pusher** [comment]
Hi @kaggrwal, we are experiencing some delays with our swag supplier but we will ensure you are kept up to date on the distribution. Please keep an eye on the email address you used to request your swag.

**Comment by Parajulibkrm** [comment]
Is there any update? I haven't received a single update yet.

**Comment by kaggrwal** [comment]
@Parajulibkrm I have received the swags 2-3 days ago, they are sending it out.  So, don't worry, you will receive it soon.
